DROP TABLE IF EXISTS MODULE;
DROP TABLE IF EXISTS COW;
DROP TABLE IF EXISTS BULL;
--DROP TABLE IF EXISTS MATE;
--DROP TABLE IF EXISTS LACTATION;

CREATE TABLE MODULE(
    ID INTEGER PRIMARY KEY,
    NAME TEXT,
    ICON TEXT,
    DESCRIPTION TEXT,
    ACTIVITY TEXT
);

CREATE TABLE COW(
    ID INTEGER PRIMARY KEY,
    PUBLIC_ID TEXT,
    NAME TEXT,
    NUMBER TEXT,
    BOOK TEXT,
    BULL_ID INTEGER,
    BIRTHDAY TEXT
);

CREATE TABLE BULL(
    ID INTEGER PRIMARY KEY,
    PUBLIC_ID TEXT,
    NAME TEXT,
    NUMBER TEXT
);

--CREATE TABLE MATE(
--    ID INTEGER PRIMARY KEY,
--    PUBLIC_ID TEXT,
--    DATE TEXT,
--    COW_ID INTEGER,
--    BULL_ID INTEGER
--);
--
--CREATE TABLE LACTATION(
--    ID INTEGER PRIMARY KEY,
--    PUBLIC_ID TEXT,
--    DATE TEXT,
--    COW_ID INTEGER
--);

INSERT INTO MODULE(ID, PUBLIC_ID, NAME, DESCRIPTION, IMAGE) VALUES (
    null, "190c131f-9093-4874-aec3-f02a687e422a", "Moje krowy", "Zarządzaj swoimi krowami", "/ic_my_cows.png");
INSERT INTO MODULE(ID, NAME, ICON, DESCRIPTION, ACTIVITY) VALUES (
    null, "3f0af628-393e-4738-8bc8-266100857804", "Moje buhaje", "Zarządzaj swoimi buhajami", "/ic_my_bulls.png");